### ISSUE TITLE
portmap: delete UDP conntrack entries on teardown

### ISSUE THREAD

**Issue by squeed** [containernetworking/plugins#123]
As observed in kubernetes/kubernetes#59033, a quick teardown + spinup of portmappings can cause UDP "flows" to be lost, thanks to stale conntrack entries.

From the original issue:

> 1. A server pod exposes UDP host port.
> 2. A client sends packets to the server pod thru the host port. This creates a conntrack entry.
> 3. The server pod's IP changs due to whatever reason, such as pod gets recreated.
> 4. Due to the nature of UDP and conntrack, new request from the same client to the host port will keep hitting the stale conntrack entry.
> 5. Client observes traffic black hole.

**Comment by brantburnett** [comment]
I have found that this bug doesn't seem to only apply to changing pod IPs.  It can also apply if there is incoming traffic that is being dropped because there is no pod, and then a pod is added that should start receiving the traffic.

Complete details and steps to reproduce: https://github.com/projectcalico/felix/issues/1880

**Comment by vmendi** [comment]
We are also affected by this.  We lose metrics whenever there's a restart of the Datadog agent. Is there any plans to fix it? any workaround available?

Thanks

**Comment by Suckzoo** [comment]
Seems like this issue has been opened for a year. Is there any plan to fix this issue? Or, could you let me know how to fix this problem by my hand?

**Comment by RohanKurane** [comment]
Hello,

I think I am hitting a similar issue. 

I deploy a pod with ```hostport``` and created using ```type:portmap```. 
Then when I try to delete the pod, and re-deploy the same pod with same name, I get the following error - 
```Warning  FailedCreatePodSandBox  1m    kubelet, ip-xxxxxxxxx.ec2.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_server_default_436fb151-71b1-11e9-b2d9-128d1a3304a4_0(7993b317dc75381c0ed08a75019fde6c2fe70aaf5697af6cc1f0e85c7afddfd6): cannot open hostport 50051 for pod k8s_server_default_436fb151-71b1-11e9-b2d9-128d1a3304a4_0_: listen tcp :50051: bind: address already in use
```

Is this the same issue ? If so, is there a workaround till this issue is fixed ? 

Thanks

**Comment by Simwar** [comment]
It seems like this PR aimed to fix the issue: https://github.com/kubernetes/kubernetes/pull/59286
But this one is needed to have the conntrack binary installed as well in the right path I believe: https://github.com/kubernetes/kubernetes/pull/64640
On GKE for example, as you need to run the conntrack binary via the toolbox (`toolbox conntrack -D -p udp`)

**Comment by msiebuhr** [comment]
I've experimented a bit with this, and there's some small fixes -- in particular, `conntrack` exits with code 1 if no connections are deleted, causing the pod to get stuck in a init-loop.

As to the container, I've used `gcr.io/google-containers/toolbox:20190523-00` ([overview here](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/toolbox)).

```yaml
initContainers: 
    - image: 'gcr.io/google-containers/toolbox:20190523-00'
      imagePullPolicy: 'IfNotPresent '
      name: 'conntrack'
      securityContext: 
       allowPrivilegeEscalation: true 
         capabilities: 
           add: ["NET_ADMIN"] 
      command: ['sh', '-c', 'conntrack -D -p udp --dport 8125 | true']
```

(I'm having an issue with statsd + datadog, which uses UDP 8125, so I'm only deleting that).

**Comment by msiebuhr** [comment]
The above does seem to fix things for low-traffic client services, but our high-traffic services seem to get new `conntrack` entries set up between running the `initContainer` and (in our case) `datadog-agent` starting up.

If I SSH into the machine and manually run the conntrack-command, things come back as expected.

**Comment by raghurampai** [comment]
This issue still exists in the latest. I encountered this issue with DaemonSet for the same scenario mentioned in the description. The workaround does has corner case as mentioned by msiebuhr.   

Anyone was able to solve it in any alternate way?

**Comment by AnishShah** [comment]
I can work on this issue. Is it okay if we just flush conntrack entries just like it is done in kubernetes/kubernetes#59286? Are there any concerns?

**Comment by aojea** [comment]
I have a PR for this, let me check something first,

**Comment by aojea** [comment]
nevermind @AnishShah , you deserve the honor, I just see the comment in the k/k issue.
sorry

**Comment by aojea** [comment]
@AnishShah this is the approach I was taken https://github.com/containernetworking/plugins/compare/master...aojea:conntrack?expand=1 , feel free to reuse it or discard it.
@squeed can you help us here?

**Comment by AnishShah** [comment]
@aojea Since you have already created the PR, you can go ahead with it

**Comment by AnishShah** [comment]
@aojea I had a brief look at your PR. I think we should delete UDP conntrack entries on teardown and setup both. Even in  kubernetes/kubernetes#59286, it seems that we are deleting conntrack entries when we setup hostport iptable rules.

I tested your PR with a udp client/server pods

```
apiVersion: v1
kind: Namespace
metadata:
  name: udp
---
apiVersion: v1
kind: Pod 
metadata:
  name: udp-server
  namespace: udp
spec:
    containers:
      - name: udp-server
        image: aardvarkx1/udp-server
        imagePullPolicy: Always
        ports:
          - containerPort: 10001
            protocol: UDP
            hostPort: 10001
            name: udp-test
---
apiVersion: v1
kind: Pod
metadata:
  name: udp-client
  namespace: udp
spec:
    containers:
      - name: udp-client
        image: aardvarkx1/udp-client
        imagePullPolicy: Always
        env:
          - name: SERVER_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
```

I notice one conntrack entry with

```
sudo conntrack -L -p UDP --orig-port-dst 10001
udp      17 29 src=10.8.0.19 dst=10.128.0.71 sport=33371 dport=10001 [UNREPLIED] src=10.8.0.24 dst=10.128.0.71 sport=10001 dport=33371 mark=0 use=1
conntrack v1.4.4 (conntrack-tools): 1 flow entries have been shown.
```

When I deleted udp-server, the conntrack entry changed to

```
sudo conntrack -L -p UDP --orig-port-dst 10001
udp      17 28 src=10.8.0.19 dst=10.128.0.71 sport=33371 dport=10001 [UNREPLIED] src=10.128.0.71 dst=10.8.0.19 sport=10001 dport=33371 mark=0 use=1
conntrack v1.4.4 (conntrack-tools): 1 flow entries have been shown.
```

Notice the change in src/dst IP for reply direction. When I created udp-server pod again, I don't see any changes in conntrack entry. It is the same as above. I ensured that the DNAT rules are created.
