### ISSUE TITLE
Bridge/Host-local: Any guard-rails to not schedule pods on the nodes where IPs are exhausted

### ISSUE THREAD

**Issue by Purushotham233** [containernetworking/plugins#338]
We are using CNI plugins bridge/host-local on nodes with limited pool of IPs which can be exhaused before any other resource(cpu/mem etc).

In such case, how can I ensure the pods are not scheduled to the nodes where IPs are exhaused but the resources are still available. Are they are any in-built guard-rails in k8s scheduler? If not is there any way to taint the nodes once the IPs are exhausted.

**Comment by squeed** [comment]
Unfortunately, you've discovered an unfortunate shortcoming in the way pods are scheduled in kubernetes. The assumption is that the node's IP pool is much larger than the maximum number of pods.

However, there are some things you can do. You can set `--max-pods` to limit the number of pods that can run on a node, but HostNetwork pods will count against this limit, even though they don't consume IP addresses.

You also need to deal with sandbox GC - when a pod is deleted, its IP address isn't immediately removed. These are reclaimed every minute. There used to be a parameter that would trigger garbage collection earlier, but it has been removed.

If you think the number of IPs should be a schedulable property in kubernetes, then you should consider reaching out to the scheduler team and trying to add that. I would suggest, if at all possible, to switch to an ipv6 cluster, where you'll never run out of IPs :-)

**Comment by mars1024** [comment]
I think CNI is stateless so we can't expect it to taint node.
I have a light solution to involve IP count in scheduling, through [extended resource](https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/), we can patch IP count to **node.status.capacity**, like
```
Capacity:
 cpu:  2
 memory:  2049008Ki
 ip: 60
```
When we want to create a non-hostnetwork pod, we will add a IP **request** and **limit** to it manually or through [admission controller](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/), like
```
apiVersion: v1
kind: Pod
metadata:
  name: extended-resource-demo
spec:
  containers:
  - name: extended-resource-demo
    image: nginx
    resources:
      requests:
        ip: 1
      limits:
        ip: 1
```
This will let IP count participate in scheduling.
