### ISSUE TITLE
bandwidth annotation doesn't match the output of iperf3

### ISSUE THREAD

**Issue by lazywhite** [containernetworking/plugins#465]
## cni bandwidth plugin version
```
ubuntu@gpu0-222:/opt/cni/bin$ ./bandwidth -h
CNI bandwidth plugin v0.8.0
```
## pod manifest
```
apiVersion: v1
kind: Namespace
metadata:
  name: policy-demo
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
  labels:
    app: iperf-server
  namespace: policy-demo
spec:
  restartPolicy: OnFailure
  containers:
  - name: iperf-server
    image: networkstatic/iperf3
    args: [ "-s" ]
    ports:
    - containerPort: 5201
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-server
  labels:
    app: iperf-server
  namespace: policy-demo
spec:
  ports:
  - port: 5201
    targetPort: 5201
  selector:
    app: iperf-server

---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client5
  labels:
    app: iperf-client5
  namespace: policy-demo
  annotations:
    kubernetes.io/ingress-bandwidth: 1000M
    kubernetes.io/egress-bandwidth: 1000M
spec:
  restartPolicy: OnFailure
  containers:
  - name: iperf-client5
    image: networkstatic/iperf3
    args: [ "-c",  "iperf-server", "-t", "30" ]
```
## iperf client output
```
[  4] local 192.168.0.83 port 57428 connected to 10.108.41.119 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  27.1 MBytes   227 Mbits/sec    1    605 KBytes
[  4]   1.00-2.00   sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]   3.00-4.00   sec   738 KBytes  6.05 Mbits/sec    0    605 KBytes
[  4]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]   5.00-6.00   sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]   9.00-10.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  10.00-11.00  sec   686 KBytes  5.62 Mbits/sec    0    605 KBytes
[  4]  11.00-12.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  12.00-13.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  13.00-14.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  14.00-15.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  15.00-16.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  16.00-17.00  sec   686 KBytes  5.62 Mbits/sec    0    605 KBytes
[  4]  17.00-18.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  18.00-19.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  19.00-20.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  20.00-21.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  21.00-22.00  sec   686 KBytes  5.62 Mbits/sec    0    605 KBytes
[  4]  22.00-23.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  23.00-24.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  24.00-25.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  25.00-26.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  26.00-27.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  27.00-28.00  sec   686 KBytes  5.62 Mbits/sec    0    605 KBytes
[  4]  28.00-29.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
[  4]  29.00-30.00  sec  0.00 Bytes  0.00 bits/sec    0    605 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-30.00  sec  30.5 MBytes  8.53 Mbits/sec    1             sender
[  4]   0.00-30.00  sec  28.8 MBytes  8.06 Mbits/sec                  receiver
```

## Question
1. what's the unit of annotation, 1000M(bps, Bps)?
2. why specified 1000M, but output 8Mbps,
