### ISSUE TITLE
Proposal: Introducing a VRF CNI metaplugin

### ISSUE THREAD

**Issue by fedepaol** [containernetworking/plugins#516]
Hi, I am opening this issue to propose to introduce an additional CNI meta plugin to add an interface to a [VRF](https://www.kernel.org/doc/Documentation/networking/vrf.txt). It would take the VRF name as an input, and could be chained to the “main” cni, having the effect of creating the requested VRF (if it does not exist) and adding the interface to that VRF.

In this way, the network interface returned by any CNI can be isolated in its own VRF, making it possible to have different interfaces belonging to different VRFs (eventually, with overlapping CIDRs) in the container's namespace.

A configuration would look like

```yaml
             {
              "cniVersion": "0.3.1",
              "plugins": [
                {
                  "type": "macvlan",
                  "mode": "bridge",
                  "ipam": {
                    "type": "host-local",
                    "subnet": "192.168.1.0/24",
                    "rangeStart": "192.168.1.200",
                    "rangeEnd": "192.168.1.216",
                  }
                },
                {
                  "type": "vrf",
                  "vrfname": "blue"
                }
              ]
            }
```

The CNI implementation would be pretty simple: it takes the result of the main CNI, creates the VRF in the pod's namespace and assignes the interface to the VRF.

If the VRF already exists, it only adds the interface. When removing an interface, it does the same, checking if the interface is the last removed from the VRF and eventually delete the VRF.

Normally, a VRF is associated with a routing table id, but to keep the api simple we would generate the tableid inside the CNI, hiding it from the user.
