### ISSUE TITLE
VLAN not working with bridge plugin

### ISSUE THREAD

**Issue by rootfs** [containernetworking/plugins#533]
Hi I am running an issue with bridge plugin with VLANs. 

I have a Linux gateway that has a bonding network. I built a bridge and assign VLAN to it. In the net-attach-def, I use that VLAN and give it to a Pod. But I exec into the pod, I cannot ping the gateway from there. I did another test without VLAN, then ping from the Pod can reach to the gateway.  So this issue looks solely related to vlan.

# gateway setting
```bash
ip link del bond0.201
ip link del br0.201

ip link add link bond0 name bond0.201 type vlan id 201
ip link add br0.201 type bridge vlan_filtering 1
ip link set bond0.201 master br0.201
bridge vlan add dev bond0.201 vid 201 pvid untagged
ip addr add 10.123.123.1/24 dev bond0.201
ip link set up dev br0.201
ip link set up dev bond0.201
```
The `bridge vlan` output is as below
```
bridge vlan
port    vlan ids
bond0    1 PVID Egress Untagged

bond0
bond0.201        1 Egress Untagged
         201 PVID

bond0.201
br0.201  1 PVID Egress Untagged
         201
```
# Node
The node where the pod runs can ping the gateway and see the veth with vlan
```console
sh-4.4# bridge vlan show dev veth6884bf76
port    vlan ids
veth6884bf76
         1 untagged      201 PVID untagged
```
# Pod and net-attach-def
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-conf
  namespace: playground
spec:
  config: '{
          "name": "my-whereabouts",
          "type": "bridge",
          "bridge": "br1",
          "vlan": 201,
          "ipam": {
            "type": "whereabouts",
            "range": "10.123.123.0/24",
            "range_start": "10.123.123.4",
            "range_end": "10.123.123.200",
            "routes": [
                { "dst": "0.0.0.0/0", "gw" : "10.123.123.1" }
            ]
           }
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: playground
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        { "name": "net-conf",
          "default-route": [ "10.123.123.1" ] }
    ]'
spec:
  containers:
  - name: centos
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
    securityContext:
      privileged: true
```

# Pod ping test
```console
# kubectl exec -ti -n playground centos sh
sh-4.2# ping 10.123.123.1
PING 10.123.123.1 (10.123.123.1) 56(84) bytes of data.
From 10.123.123.5 icmp_seq=1 Destination Host Unreachable
From 10.123.123.5 icmp_seq=2 Destination Host Unreachable
From 10.123.123.5 icmp_seq=3 Destination Host Unreachable
From 10.123.123.5 icmp_seq=4 Destination Host Unreachable
From 10.123.123.5 icmp_seq=5 Destination Host Unreachable
From 10.123.123.5 icmp_seq=6 Destination Host Unreachable
^C
--- 10.123.123.1 ping statistics ---
8 packets transmitted, 0 received, +6 errors, 100% packet loss, time 7202ms
```

@s1061123 @dcbw
