### ISSUE TITLE
failed to create VRF by using vrf plugin

### ISSUE THREAD

**Issue by nokia-t1zhou** [containernetworking/plugins#597]
hi, I am want to use the vrf plugin to create the VRF in container, below is my CNI configuration:
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-vrf-test
  namespace: cran3
  annotations:
    k8s.v1.cni.cncf.io/resourceName: aae.k8s.io/sriov_ens9f0
spec:
  config: '{
      "cniVersion": "0.4.0",
      "plugins": [
        {
          "type": "sriov",
          "ipam": {
              "type": "host-local",
              "subnet": "192.168.20.0/24",
              "rangeStart": "192.168.20.200",
              "rangeEnd": "192.168.20.216"
          }
        },
        {
          "type": "vrf",
          "vrfname": "zt1"
        }
      ]
    }'
```
and use below pod yaml to deploy it:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zt
spec:
  selector:
    matchLabels:
      app: zt-app
  template:
    metadata:
      labels:
        app: zt-app
      annotations:
        k8s.v1.cni.cncf.io/networks: sriov-vrf-test@test1
.....
.....
.....
```
 but after the pod is running, i can't find the VRF in container,  the wanted SRIOV interface is created in container default VRF. the "ip addr show" display is as below:
```
 [root@zt-0 /]# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
......
......
......
7: zt1: <NOARP,MASTER,UP,LOWER_UP> mtu 65536 qdisc noqueue state UP group default
    link/ether be:2b:57:60:4f:18 brd ff:ff:ff:ff:ff:ff
53: test1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master zt1 state UP group default qlen 1000
    link/ether d2:58:eb:4e:29:c4 brd ff:ff:ff:ff:ff:ff
    inet 192.168.20.203/24 brd 192.168.20.255 scope global test1
       valid_lft forever preferred_lft forever
```
**It is very strange that a new interface is generated and using the name of vrf "zt1".**
