### ISSUE TITLE
Feature request: support static routes with dhcp ipam plugin

### ISSUE THREAD

**Issue by jhoblitt** [containernetworking/plugins#640]
I am using the `dhcp` plugin with multus to add interfaces to pods to provide access to vlans/subnets which are part of a part of independent vrf.  The number of pods is dynamic and dhcp is the only reasonable option for management.  It is not possible to access these subnets via the k8s default overlay.  I have resorted to using a privileged init container (https://github.com/lsst-it/ddsnet4u) to inject static routes into pods in order to make using the `dhcp` plugin feasible.

It would reduce management complexity and remove the need for privileged init containers if the `dhcp` plugin supported setting static routes similar to the `static` plugin.  E.g.:

```yaml
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: auxtel-dds
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "br42",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp",
        "routes": [
          { "dst": "10.0.0.0/28", "gw": "192.168.1.1" },
          { "dst": "10.0.0.128/27", "gw": "192.168.1.1" }
        ]
      }
    }'
```
