### ISSUE TITLE
`dhcp daemon` cannot use anything different from `eth0`

### ISSUE THREAD

**Issue by dilyanpalauzov** [containernetworking/plugins#761]
On my laptop I have no eth0 interface.  I have `wlp2s0`, which I want to use with `dhcp daemon`.  https://www.cni.dev/plugins/current/main/macvlan/#notes says for macvlan on laptops 
> If you are testing on a laptop, please remember that most wireless cards do not support being enslaved by macvlan.

This does not mean, that my wireless card cannot support the configuration, so I want to give it a try.

The kernel logs `Jul 24 18:02:56 d kernel: eth0: renamed from veth5d8b8746` and `dhcp daemon` prints
```
2022/07/24 18:02:56 2cdea54c113ac6f2ac19e2746962ec8c9f000bc4b6c19ea1edda3526d7928bc2/11-crio-macvlan.conf/eth0: acquiring lease
2022/07/24 18:02:56 Link "eth0" down. Attempting to set up
2022/07/24 18:02:56 network is down
2022/07/24 18:02:56 retrying in 4.881018 seconds
2022/07/24 18:02:56 7d9df53566c423b66749431e5a68f7a7160cd72b566a81bc83f9eefac51b2605/11-crio-macvlan.conf/eth0: acquiring lease
2022/07/24 18:02:56 Link "eth0" down. Attempting to set up
2022/07/24 18:02:56 network is down
2022/07/24 18:02:56 retrying in 4.329120 seconds
2022/07/24 18:03:11 no DHCP packet received within 10s
2022/07/24 18:03:11 retrying in 7.875428 seconds
2022/07/24 18:03:11 no DHCP packet received within 10s
2022/07/24 18:03:11 retrying in 7.849275 seconds
2022/07/24 18:03:29 no DHCP packet received within 10s
2022/07/24 18:03:29 retrying in 16.373646 seconds
2022/07/24 18:03:29 no DHCP packet received within 10s
2022/07/24 18:03:29 retrying in 15.131274 seconds
```
That said, there is no documented way for `dhcp daemon` to use something different from `eth0` and I have no `eth0`.  I want to use `wlp2s0` instead of `eth0`.

**Comment by mccv1r0** [comment]
I suspect that eth0 comes from the [CNI_IFACENAME environment variable](https://www.cni.dev/docs/spec/#parameters) supplied on cniADD, which defaults to eth0.

Which interface the dhcp ipam uses is a function of the main plugin (e.g. [macvlan](https://www.cni.dev/plugins/current/main/macvlan/#example-configuration)).  If your macvlan plugin config uses `"master": "wlp2s0",`the dhcp plugin will use this interface on your laptop.

Do you have a dhcp server at the other end of wlps20 that will assign addresses?   The dhcp daemon is a server to CNI plugins and not a dhcp server itself.

**Comment by dilyanpalauzov** [comment]
I start 
> rm -f /run/cni/dhcp.sock && CNI_IFNAME=wlp2s0 strace -fs2048 /opt/cni/bin/dhcp daemon |& tee dhcp-strace.log

This is my /etc/cni/net.d/11-crio-ipv4-bridge.conflist file.

<details>
<summary>11-crio-ipv4-bridge.conflist</summary>

```
{
    "cniVersion": "1.0.0",
    "name": "crio",
    "plugins": [
      {
	"type": "macvlan",
	"master": "eth0",
	"ipam": {
            "type": "dhcp",
            "requests": [{"skipDefault": false}],
            "provide": [
                {
                   "option": "host-name",
                   "fromArg": "K8S_POD_NAME"
                }
             ]
	}
      }
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      },
      "externalSetMarkChain": "KUBE-MARK-MASQ"
    },
    {
      "type": "firewall"
    }, {
       "type": "tuning"
    }
  ]
}
```
</details>

I create the cluster with `kubeadm init --config /root/kubeadm-macvlan.config`, where
<details>
<summary>kubeadm-macvlan.config</summary>

```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
failSwapOn: false
fileCheckFrequency: 4h
cgroupDriver: systemd
featureGates:
  EphemeralContainers: true
  NodeSwap: true
syncFrequency: 5m
tlsMinVersion: VersionTLS13
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs # or "userspace" or "iptables"
featureGates:
  EphemeralContainers: true
  NodeSwap: true
conntrack:
# Skip setting sysctl value "net.netfilter.nf_conntrack_max"
  maxPerCore: 0
# Skip setting "net.netfilter.nf_conntrack_tcp_timeout_established"
  tcpEstablishedTimeout: 0s
# Skip setting "net.netfilter.nf_conntrack_tcp_timeout_close"
  tcpCloseWaitTimeout: 0s
```
</details>

I have a dhcp server on the other end of the wlp2s0 connection.  When I create a pod it gets the error

>   Warning  FailedCreatePodSandBox  93s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_karana_default_357eba5f-4c60-4e94-aa77-3246ba65ba59_0(6e2e124d15a83e2d8ae046ae2a4279872a6a5a35195e72845162935ae1a02940): error adding pod default_karana to CNI network "crio-macvlan": plugin type="macvlan" failed (add): Link not found

Here is the output of strace: [dhcp-strace.log](https://github.com/containernetworking/plugins/files/9329098/dhcp-strace.log).

Any idea what is wrong?
